sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

language: node_js
node_js:
  - "8.10.0"

before_install:
  - npm install
  - export CHROME_BIN=/usr/bin/google-chrome
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - gulp pre-publish

before_cache:
- sudo chown -R travis:travis node_modules
- sudo chown -R travis:travis packages/spark-core/node_modules
- sudo chown -R travis:travis packages/spark-extras-highlight-board/node_modules

cache:
  directories:
  - node_modules
  - packages/spark-core/node_modules
  - packages/spark-extras-highlight-board/node_modules
