language: node_js

install:
- npm install
- npm install --prefix ./packages/spark-core
- npm install --prefix ./packages/spark-extras/components/highlight-board

before_script:
- npm run test --prefix ./packages/spark-core

cache:
  directories:
    - node_modules
    - packages/spark-core/node_modules
