[[redirects]]
  from = "/gettingstarted/angular"
  to = "/installing-spark/angular"
  status = 301

[[redirects]]
  from = "/gettingstarted/design-principles"
  to = "/principles/design-principles"
  status = 301

[[redirects]]
  from = "/gettingstarted/html"
  to = "/installing-spark/html"
  status = 301

[[redirects]]
  from = "/gettingstarted/react"
  to = "/installing-spark/react"
  status = 301

[[redirects]]
  from = "/patterns/fundamentals/grid"
  to = "/using-spark/components/stack"
  status = 301

[[redirects]]
  from = "/patterns/fundamentals/space#stack"
  to = "/using-spark/components/stack"
  status = 301

[[redirects]]
  from = "/patterns/fundamentals/layers"
  to = "/using-spark/foundations/sass-variables"
  status = 301

[[redirects]]
  from = "/patterns/fundamentals/layout"
  to = "/using-spark/components/stack"
  status = 301

[[redirects]]
  from = "/patterns/fundamentals/*"
  to = "/using-spark/foundations/:splat"
  status = 301

[[redirects]]
  from = "/patterns/components/*"
  to = "/using-spark/components/:splat"
  status = 301

[[redirects]]
  from = "/patterns/utilities/*"
  to = "/using-spark/foundations/css-utilities"
  status = 301

[[redirects]]
  from = "/docs/accessibility"
  to = "/principles/accessibility-guidelines"
  status = 301

[[redirects]]
  from = "/docs/change-workflow"
  to = "https://github.com/sparkdesignsystem/spark-design-system/blob/main/CONTRIBUTING.md"
  status = 301

[[redirects]]
  from = "/docs/class-naming-convention"
  to = "/principles/class-naming-convention"
  status = 301

[[redirects]]
  from = "/docs/contributions"
  to = "https://github.com/sparkdesignsystem/spark-design-system/blob/main/CONTRIBUTING.md"
  status = 301

[[redirects]]
  from = "/docs/release-notes"
  to = "https://github.com/sparkdesignsystem/spark-design-system/releases"
  status = 301

# Add redirects for pluralized component names
[[redirects]]
  from = "/patterns/components/alerts"
  to = "/using-spark/components/alert"
  status = 301

[[redirects]]
  from = "/patterns/components/accordions"
  to = "/using-spark/components/accordion"
  status = 301

[[redirects]]
  from = "/patterns/components/awards"
  to = "/using-spark/components/award"
  status = 301

[[redirects]]
  from = "/patterns/components/buttons"
  to = "/using-spark/components/button"
  status = 301

[[redirects]]
  from = "/patterns/components/dividers"
  to = "/using-spark/components/divider"
  status = 301

[[redirects]]
  from = "/patterns/components/icons"
  to = "/using-spark/components/icon"
  status = 301

[[redirects]]
  from = "/patterns/components/links"
  to = "/using-spark/components/link"
  status = 301

[[redirects]]
  from = "/patterns/components/lists"
  to = "/using-spark/components/list"
  status = 301

[[redirects]]
  from = "/patterns/components/modals"
  to = "/using-spark/components/modal"
  status = 301

[[redirects]]
  from = "/patterns/components/tables"
  to = "/using-spark/components/table"
  status = 301

[[redirects]]
  from = "/patterns/components/inputs"
  to = "/using-spark/components/input"
  status = 301

[[redirects]]
  from = "using-spark/foundations/color"
  to = "/using-spark/foundations/color-usage"
  status = 301

[[redirects]]
  from = "/using-spark/foundations/sass-variables"
  to = "/using-spark/foundations/design-tokens"
  status = 301


